---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: dist
    force_apt_get: yes

- name: "nodesource installation"
  become: yes
  shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
  


- name: "install nodejs"
  become: yes
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: "install pm2"
  npm:
    name: pm2
    global: yes

- name: "create directory"
  file:
    path: ~/web
    state: directory

- name: "copy customer server to created directory"
  copy:
    src: files/index.js
    dest: ~/web/index.js


- name: "start index.js"
  shell: pm2 start ~/web/index.js -f
  
# this worked for ubuntu with this image 'ami-09e67e426f25ce0d7' 